apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - radix-acr-cleanup.yaml
  - radix-cicd-canary.yaml
  - radix-cost-allocation.yaml
  - radix-operator.yaml
  - radix-platform.yaml
  - radix-vulnerability-scanner.yaml
