apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radix-operator
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./components/radix-platform/radix-operator
  prune: false
  postBuild:
    substitute:
      GIT_CLONE_TAG: "2.45.2"
      OAUTH2PROXY_TAG: "v7.15.2"
      OAUTH2REDIS_TAG: "8.6.0-alpine3.23"
      RADIX_APP_ACR_REPO_URL: radixc3app.azurecr.io
      RADIX_BUILDKIT_IMAGE_BUILDER_TAG: "1.0.1" # {"$imagepolicy": "flux-system:radix-buildkit-builder:tag"}
      RADIX_IMAGE_BUILDER_TAG: "1.0.0" # {"$imagepolicy": "flux-system:radix-image-builder:tag"}
      RADIX_OPERATOR_CHART_VERSION: 1.114.3-rc.1 # {"$imagepolicy": "flux-system:radix-operator-chart:tag"}
      RADIX_PIPELINE_GIT_CLONE_BASH_IMAGE: radixc2cache.azurecr.io/bash:5.2
      RADIX_PIPELINE_GIT_CLONE_GIT_IMAGE: radixc2cache.azurecr.io/alpine/git:2.45.2
      RADIX_PIPELINE_GIT_CLONE_NSLOOKUP_IMAGE: radixc2cache.azurecr.io/alpine:3.20
      RADIX_SECCOMP_PROFILE_INSTALLER_IMAGE: radixc2cache.azurecr.io/alpine:3.20
      SECCOMP_IMAGE_TAG: 3.22.1

      oidcKubernetesIssuer: "https://swedencentral.oic.prod-aks.azure.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/8b1c9802-20bf-43d0-8689-bd4ad8449b53/"
      oidcKubernetesAudience: "https://swedencentral.oic.prod-aks.azure.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/8b1c9802-20bf-43d0-8689-bd4ad8449b53/"
      clusterOidcIssuers: "https://swedencentral.oic.prod-aks.azure.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/8b1c9802-20bf-43d0-8689-bd4ad8449b53/"
      clusterEgressIps: "51.107.182.144/28,51.107.181.16/28,51.107.182.192/28"
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: radix-operator
          namespace: default
        spec:
          values:
            resources:
              limits:
                cpu: "2"
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 1Gi

      target:
        kind: HelmRelease
        name: radix-operator
        namespace: default
