apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radix-acr-cleanup
  namespace: default
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  chartRef:
    kind: OCIRepository
    name: radix-acr-cleanup-chart
    namespace: flux-system
  values:
    clusterType: ${clusterType} # Read from radix-flux-config configmap
    activeClusterName: ${ACTIVE_CLUSTER} # Set by zone-specific overlay
    currentClusterName: ${clusterName} # set in radix-flux-config configmap
    registry: ${imageRegistry}
    deleteUntagged: true
    retainLatestUntagged: 0
    performDelete: true
    period: 1h
    cleanupStart: "0:00"
    cleanupEnd: "06:00"
    metrics:
      enabled: true
    securityContext:
      readOnlyRootFilesystem: true
    extraVolumes:
      - name: tmp
        emptyDir:
          sizeLimit: 1M
      - name: azurehome
        emptyDir:
          sizeLimit: 100M
    extraVolumeMounts:
      - name: tmp
        mountPath: /tmp
      - name: azurehome
        mountPath: /home/nonroot/.azure
      - name: azurehome # TODO: Backward-compatibility with old acr-cleanup users. remove after radix-acr-cleanup merged to release and installed in all clusters
        mountPath: /home/acr-cleanup/.azure
    whitelisted:
      - radix-operator
      - radix-pipeline
      - rx
      - buildx
      - radix-cicd-canary
      - radix-image-builder
      - radix-image-builderx
      - radix-tekton
      - radix-image-scanner
      - radix-acr-cleanup
      - gitclone
      - radix-velero-plugin
      - sima-runtime
      - radix-config-2-map
      - radix-cost-allocation
      - radix-job-scheduler-server
      - radix-job-scheduler
      - radix-batch-scheduler
      - radix-vulnerability-scanner
      - oauth2-proxy
      - radix-buildkit-builder
      - radix-cluster-cleanup
      - radix-buildah-image-builder
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 250Mi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - arm64
