apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: default
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    rbac:
      create: true
    interval: 60s
    txtOwnerId: ${clusterName}
    provider: azure
    azure:
      resourceGroup: common
      secretName: external-dns-azure-secret
    domainFilters:
      - ${dnsZone}
    policy: sync
    podAnnotations: {prometheus.io/scrape: "true",prometheus.io/port: "7979"}
    metrics:
      enabled: true
    resources:
      limits:
        cpu: "6"
        memory: 512Mi
      requests:
        cpu: 25m
        memory: 512Mi
    priorityClassName: radix-component-priority
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-cnames
  namespace: default
spec:
  releaseName: external-dns-cnames
  chart:
    spec:
      chart: external-dns
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    rbac:
      create: true
    interval: 15s
    crd:
      create: true
    txtSuffix: "-ownerrecord"
    logLevel: info
    labelFilter: "radix-is-external-dns-source=true"
    command: ["/radixmount/entrypoint.bash"]
    sources:
      - crd
    extraVolumes:
    - name: entrypoint
      configMap:
        name: entrypoint
        defaultMode: 0700
    extraVolumeMounts:
    - name: entrypoint
      mountPath: /radixmount
    provider: azure
    azure:
      resourceGroup: common
      secretName: external-dns-azure-secret
    domainFilters:
      - ${dnsZone}
    policy: sync
    podAnnotations: {prometheus.io/scrape: "true",prometheus.io/port: "7979"}
    metrics:
      enabled: true
    resources:
      limits:
        cpu: "6"
        memory: 512Mi
      requests:
        cpu: 25m
        memory: 512Mi
    priorityClassName: radix-component-priority
---
apiVersion: v1
data:
  entrypoint.bash: |
    #!/bin/bash
    if [ "${clusterName}" == "${ACTIVE_CLUSTER}" ]
    then 
      txtOwnerId=active-cluster-cname
    else 
      txtOwnerId=${clusterName}-cname
    fi
    external-dns --txt-owner-id=$${txtOwnerId} "$@"
kind: ConfigMap
metadata:
  name: entrypoint
  namespace: default