apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: default
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    rbac:
      create: true
    interval: 60s
    txtOwnerId: ${clusterName}
    provider: azure
    azure:
      resourceGroup: common
      secretName: external-dns-azure-secret
    domainFilters:
      - ${dnsZone}
    policy: sync
    podAnnotations: {prometheus.io/scrape: "true",prometheus.io/port: "7979"}
    metrics:
      enabled: true
    resources:
      limits:
        cpu: "6"
        memory: 512Mi
      requests:
        cpu: 25m
        memory: 512Mi
    priorityClassName: radix-component-priority
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns-cnames
  namespace: default
spec:
  releaseName: external-dns-cnames
  chart:
    spec:
      chart: external-dns
      version: xx # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    rbac:
      create: true
    interval: 15s
    crd:
      create: true
    txtSuffix: "-ownerrecord"
    logLevel: info
    labelFilter: "radix-is-external-dns-source=true"
    command: ["/radixmount/entrypoint.bash"]
    sources:
      - crd
    extraVolumes:
    - name: txt-owner-id-volume
    extraVolumeMounts:
    - name: txt-owner-id-volume
      mountPath: /radixmount
    initContainers:
    - name: set-txt-owner-id
      image: alpine
      imagePullPolicy: Always
      env:
      - name: CLUSTER_NAME
        value: ${clusterName}
      - name: ACTIVE_CLUSTER
        value: ${ACTIVE_CLUSTER}
      volumeMounts:
      - name: txt-owner-id-volume
        mountPath: /radixmount
      command: ["/bin/sh", "-c", "echo IyEvYmluL2Jhc2gKZWNobyAiIyEvYmluL2Jhc2giID4gL3JhZGl4bW91bnQvZW50cnlwb2ludC5iYXNoCmlmIFsgIiR7Q0xVU1RFUl9OQU1FfSIgPT0gIiR7QUNUSVZFX0NMVVNURVJ9IiBdCnRoZW4gCiAgdHh0T3duZXJJZD1hY3RpdmUtY2x1c3RlciAKICBlY2hvICIjZXF1YWxpdHkgaG9sZHMiID4+IC9yYWRpeG1vdW50L2VudHJ5cG9pbnQuYmFzaAplbHNlIAogIHR4dE93bmVySWQ9JHtDTFVTVEVSX05BTUV9CmZpCmVjaG8gImV4dGVybmFsLWRucyAtLXR4dC1vd25lci1pZD0ke3R4dE93bmVySWR9IFwiJEBcIiIgPj4gL3JhZGl4bW91bnQvZW50cnlwb2ludC5iYXNoCmNobW9kICt4IC9yYWRpeG1vdW50L2VudHJ5cG9pbnQuYmFzaApjYXQgL3JhZGl4bW91bnQvZW50cnlwb2ludC5iYXNoCgo= | base64 --decode > /tmp/init-script.sh; chmod +x /tmp/init-script.sh; /tmp/init-script.sh"]
    provider: azure
    azure:
      resourceGroup: common
      secretName: external-dns-azure-secret
    domainFilters:
      - ${dnsZone}
    policy: sync
    podAnnotations: {prometheus.io/scrape: "true",prometheus.io/port: "7979"}
    metrics:
      enabled: true
    resources:
      limits:
        cpu: "6"
        memory: 512Mi
      requests:
        cpu: 25m
        memory: 512Mi
    priorityClassName: radix-component-priority
