apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/grafana"
  dependsOn:
    - name: external-secrets-operator
    - name: kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
    substitute:
      GRAFANA_VERSION: 12.2.1 # {"$imagepolicy": "flux-system:grafana-chart:tag"}
      GRAFANA_AR_CLIENT_ID: e1f72508-ae39-4231-87f1-27f517aa044a # gitleaks:allow
      GRAFANA_DB_HOST: s941-radix-grafana-playground.mysql.database.azure.com
      GRAFANA_DB_USERNAME: radix-id-grafana-admin-playground
      GRAFANA_WI_CLIENT_ID: f8597620-379a-40ac-9f1d-1fed7da71204 # gitleaks:allow
  wait: true
  timeout: 2m
