apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: image-update-automation
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/flux/image-update-automation"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      FLUX_CONFIG_PATH: ./clusters/playground
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
