apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  secretStoreRef:
    name: radix-keyvault
    kind: SecretStore
  refreshInterval: 5m
  target:
    name: dex-secrets
    template:
      engineVersion: v2
      data:
        DEX_AZURE_CLIENT_SECRET: "{{ .azureClientSecret }}"
  data:
    - secretKey: azureClientSecret
      remoteRef:
        key: dex-azure-client-secret
