apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ociRepo.yaml
  - imageRepo.yaml
  - imagePolicy.yaml
  - secretStore.yaml
  - externalSecret.yaml
  - helmRelease.yaml
