apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: dex
  annotations:
    azure.workload.identity/client-id: ${EXTERNAL_SECRET_MI_CLIENT_ID}
    azure.workload.identity/tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: radix-keyvault
  namespace: dex
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: workload-identity-sa
      vaultUrl: ${EXTERNAL_SECRET_URL}
