apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-oauth
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: test-oauth
  template:
    metadata:
      labels:
        app: test-oauth
    spec:
      containers:
        - env:
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: http://:4180
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: 'dummdummdummdumm'
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: 'dummdummdummdumm'
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"

            - name: OAUTH2_PROXY_PROVIDER
              value: oidc
            - name: OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS
              value: "true"
            - name: OAUTH2_PROXY_CLIENT_ID
              value: prometheus.ext-mon
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: https://northeurope.oic.prod-aks.azure.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/d11b9368-ba7a-451c-acb4-186c50caf495/
            - name: OAUTH2_PROXY_OIDC_GROUPS_CLAIM
              value: sub
            - name: OAUTH2_PROXY_ALLOWED_GROUP
              value: "system:serviceaccount:monitor:default"

          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
          name: web
          ports:
            - containerPort: 4180
              name: http
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: test-oauth
  namespace: monitor
spec:
  ports:
    - port: 4180
      protocol: TCP
      targetPort: http
  selector:
    app: test-oauth
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/auth-url: "http://test-oauth.monitor.svc.cluster.local:4180/oauth2/auth"
  labels:
    app: prometheus
  name: prometheus-oauth2-auth-v1
  namespace: monitor
spec:
  rules:
    - host: prometheus-oauth2.weekly-10.dev.radix.equinor.com
      http:
        paths:
          - backend:
              service:
                name: prometheus-operator-prometheus
                port:
                  number: 9090
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - prometheus-oauth2.weekly-10.dev.radix.equinor.com
      secretName: radix-wildcard-tls-cert
