apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitor
spec:
  releaseName: grafana
  chartRef:
    kind: OCIRepository
    name: grafana-chart
    namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: grafana
              namespace: monitor
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/volumeMounts
                value: 
                  - mountPath: /var/run/secrets/ossrdbms-aad
                    name: access-token-volume
                    readOnly: true
                  - mountPath: /var/lib/grafana
                    name: grafana-lib
                  - mountPath: /var/lib/grafana-search
                    name: grafana-search
                  - mountPath: /tmp
                    name: tmp

              - op: add
                path: /spec/template/spec/containers/0/securityContext
                value:
                  readOnlyRootFilesystem: true

              - op: add
                path: /spec/template/spec/shareProcessNamespace
                value: true
  values:
    global:
      imageRegistry: ${cacheRegistry} # set in radix-flux-config configmap

    resources:
      limits:
        cpu: 256m
        memory: 512Mi
      requests:
        cpu: 128m
        memory: 256Mi

    ingress:
      enabled: true
      hosts:
        - grafana.${clusterName}.${dnsZone}
        - grafana.${dnsZone}
      tls:
        - secretName: radix-wildcard-tls-cert
          hosts:
            - grafana.${clusterName}.${dnsZone}
            - grafana.${dnsZone}

    route:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/ttl: "30"
          radix.equinor.com/preview-gateway-mode: "true"
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: gateway
            namespace: istio-system
            sectionName: https
        hostnames:
          - grafana.${clusterName}.${dnsZone}
          - grafana.${dnsZone}
        filters:
          - responseHeaderModifier:
              add:
                - name: Strict-Transport-Security
                  value: max-age=31536000; includeSubDomains
            type: ResponseHeaderModifier

    podLabels:
      azure.workload.identity/use: "true"
      grafana.radix.equinor.com/monitor-health: "true"
    serviceAccount:
      annotations:
        azure.workload.identity/client-id: ${GRAFANA_WI_CLIENT_ID}

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
    nodeSelector: { "kubernetes.io/os": "linux" }
    env:
      GF_AUTH_DISABLE_LOGIN_FORM: "${GF_AUTH_DISABLE_LOGIN_FORM:=true}"
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_GENERIC_OAUTH_ENABLED: "false"
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"

      GF_AUTH_AZUREAD_ENABLED: "true"
      GF_AZURE_WORKLOAD_IDENTITY_ENABLED: "true"
      GF_AUTH_AZUREAD_ALLOW_ASSIGN_GRAFANA_ADMIN: "true"
      GF_AUTH_AZUREAD_CLIENT_ID: "${GRAFANA_AR_CLIENT_ID}"
      GF_AUTH_AZUREAD_AUTH_URL: "https://login.microsoftonline.com/3aa4a235-b6e2-48d5\
        -9195-7fcf05b459b0/oauth2/v2.0/authorize"
      GF_AUTH_AZUREAD_TOKEN_URL: "https://login.microsoftonline.com/3aa4a235-b6e2-48d\
        5-9195-7fcf05b459b0/oauth2/v2.0/token"
      GF_AUTH_AZUREAD_CLIENT_AUTHENTICATION: "workload_identity"
      GF_AUTH_AZUREAD_FEDERATED_CREDENTIAL_AUDIENCE: "api://AzureADTokenExchange"
      GF_AUTH_AZUREAD_ALLOWED_ORGANIZATIONS: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"

      GF_DATABASE_CA_CERT_PATH: /etc/ssl/certs/ca-certificates.crt
      GF_DATABASE_SSL_MODE: "skip-verify"
      GF_DATABASE_URL: mysql://${GRAFANA_DB_USERNAME}:$__file{/var/run/secrets/ossrdbms-aad/token}@${GRAFANA_DB_HOST}/grafana?allowCleartextPasswords=1
      GF_SERVER_ROOT_URL: https://grafana.${dnsZone}
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: "Editor" # Viewer|Editor|Admin

    extraContainerVolumes:
      - name: access-token-volume
        emptyDir: {}
      - name: grafana-lib
        emptyDir: {}
      - name: grafana-search
        emptyDir: {}
      - name: tmp
        emptyDir: {}
    extraInitContainers:
      - name: fetch-token
        image: mcr.microsoft.com/azure-cli:2.61.0
        securityContext:
          runAsUser: 472
        restartPolicy: Always
        startupProbe:
          exec:
            command: [ "sh", "-c", "[ -s /tmp/token ]" ] # Check token exist and is not empty
          initialDelaySeconds: 5
        volumeMounts:
          - name: access-token-volume
            mountPath: /tmp
        env:
          - name: HOME
            value: "/tmp"
        command:
          - "sh"
          - "-c"
          - |
            echo "$(date): starting..."
            az login --service-principal --username $AZURE_CLIENT_ID --tenant $AZURE_TENANT_ID --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" --allow-no-subscriptions
            az account get-access-token --resource-type oss-rdbms --query accessToken --output tsv > /tmp/token


            echo "$(date): Restarting grafana..."
            killall -q -SIGINT grafana # If grafana already runs, kill it so it reloads with new token

            sleepSeconds="$(jq -R 'split(".") | .[1] | @base64d | fromjson | .exp - now - 120 | floor' /tmp/token)"
            echo "$(date): Sleeping for $sleepSeconds seconds..."
            sleep "$sleepSeconds"
            echo "$(date): Finished."
