apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radix-operator
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./components/radix-platform/radix-operator
  prune: false
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
    substitute:
      GIT_CLONE_TAG: "2.45.2"
      OAUTH2PROXY_TAG: "v7.15.2"
      OAUTH2REDIS_TAG: "8.6.0-alpine3.23"
      RADIX_APP_ACR_REPO_URL: radixprodapp.azurecr.io
      RADIX_BUILDKIT_IMAGE_BUILDER_TAG: "1.0.0" # {"$imagepolicy": "flux-system:radix-buildkit-builder:tag"}
      RADIX_IMAGE_BUILDER_TAG: "1.0.0" # {"$imagepolicy": "flux-system:radix-image-builder:tag"}
      RADIX_OPERATOR_CHART_VERSION: 1.114.3-rc.1 # {"$imagepolicy": "flux-system:radix-operator-chart:tag"}
      RADIX_PIPELINE_GIT_CLONE_BASH_IMAGE: radixc2cache.azurecr.io/bash:5.2
      RADIX_PIPELINE_GIT_CLONE_GIT_IMAGE: radixc3cache.azurecr.io/alpine/git:2.45.2
      RADIX_PIPELINE_GIT_CLONE_NSLOOKUP_IMAGE: radixc2cache.azurecr.io/alpine:3.20
      RADIX_SECCOMP_PROFILE_INSTALLER_IMAGE: radixc2cache.azurecr.io/alpine:3.20
      SECCOMP_IMAGE_TAG: 3.22.1

      oidcKubernetesIssuer: "https://northeurope.oic.prod-aks.azure.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/68221e7f-018a-4359-bc19-9573d3310084/"
      oidcKubernetesAudience: "https://northeurope.oic.prod-aks.azure.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/68221e7f-018a-4359-bc19-9573d3310084/"
      clusterOidcIssuers: "https://northeurope.oic.prod-aks.azure.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/68221e7f-018a-4359-bc19-9573d3310084/"
      clusterEgressIps: "4.208.69.48/28,4.231.159.192/28,20.105.86.80/28,20.234.86.176/28,52.178.214.192/29,68.219.4.80/28,128.251.5.16/28,137.135.191.80/28"
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: radix-operator
          namespace: default
        spec:
          values:
            resources:
              limits:
                cpu: 4000m
                memory: 10Gi
              requests:
                cpu: 2000m
                memory: 8Gi
              radixZone: prod # set to platform in configmap !!!

      target:
        kind: HelmRelease
        name: radix-operator
        namespace: default
