apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/externalsecrets-v2/stores"
  dependsOn:
    - name: external-secrets-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      EXTERNAL_SECRET_URL: https://radix-keyv-platform.vault.azure.net/
      EXTERNAL_SECRET_MI_CLIENT_ID: 361d1fbc-43e9-4219-b5e9-78d7cc9aafae # gitleaks:allow
  wait: true
  timeout: 2m