apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-secrets
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/externalsecrets-v2/secrets"
  dependsOn:
    - name: external-secrets-stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      zone: prod
  wait: true
  timeout: 2m