apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-base
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/externalsecrets-v2"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      EXTERNAL_SECRET_MI_CLIENT_ID: b3f4e788-84bd-458e-9f49-d62f1c325a8d # gitleaks:allow
      EXTERNAL_SECRET_URL: https://radix-keyv-dev.vault.azure.net/
      EXTERNAL_SECRETS_VERSION: 1.2.1 # https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
  wait: true
  timeout: 2m