kind: Kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
metadata:
  name: gateway-lb
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/gateway-lb"
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: gateway-api
  patches:
    - patch: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: istio-gateway-config
        data:
          deployment: |-
            spec:
              template:
                spec:
                  containers:
                  - name: istio-proxy
                    resources:
                      requests:
                        cpu: 50m
                        memory: 100Mi
                      limits:
                        cpu: 200m
                        memory: 500Mi
      target:
        kind: ConfigMap
        name: istio-gateway-config
        namespace: istio-system