apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-lb
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/gateway-lb"
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: gateway-api
  patches:
    - patch: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: istio-gateway-config
        data:
          deployment: |-
            spec:
              template:
                metadata:
                  labels:
                    grafana.radix.equinor.com/monitor-health: "true"
                spec:
                  affinity:
                    nodeAffinity:
                      requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                        - matchExpressions:
                          - key: kubernetes.io/arch
                            operator: In
                            values:
                            - amd64
                          - key: kubernetes.io/os
                            operator: In
                            values:
                            - linux
                    podAntiAffinity:
                      preferredDuringSchedulingIgnoredDuringExecution:
                        - weight: 100
                          podAffinityTerm:
                            labelSelector:
                              matchExpressions:
                                - key: gateway.networking.k8s.io/gateway-class-name
                                  operator: In
                                  values:
                                    - istio
                                - key: gateway.networking.k8s.io/gateway-name
                                  operator: In
                                  values:
                                    - gateway
                            topologyKey: kubernetes.io/hostname
                  terminationGracePeriodSeconds: 40
                  containers:
                  - name: istio-proxy
                    resources:
                      requests:
                        cpu: 100m
                        memory: 100Mi
                      limits:
                        memory: 500Mi
                        cpu: 2000m
      target:
        kind: ConfigMap
        name: istio-gateway-config
        namespace: istio-system
