apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/grafana"
  dependsOn:
    - name: external-secrets-operator
    - name: kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
    substitute:
      GRAFANA_VERSION: 12.2.1 # {"$imagepolicy": "flux-system:grafana-chart:tag"}
      GRAFANA_AR_CLIENT_ID: f545deb5-f721-4d20-87cd-b046b5119d70 # gitleaks:allow
      GRAFANA_DB_HOST: s941-radix-grafana-dev.mysql.database.azure.com
      GRAFANA_DB_USERNAME: radix-id-grafana-admin-dev
      GRAFANA_WI_CLIENT_ID: 1150acff-2bc7-47df-a1b2-b45dbeaaf58a # gitleaks:allow
  wait: true
  timeout: 2m
