apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-issuers.yaml
  - external-dns.yaml
  - external-secrets-operator.yaml
  - external-secrets-secrets.yaml
  - external-secrets-stores.yaml
  - gateway-api.yaml
  - gateway-lb.yaml
  - grafana.yaml
  - istio-envoyfilter.yaml
  - istio.yaml
  - kubernetes-replicator.yaml
  - tekton-config.yaml
  - tekton-operator.yaml
