apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radix-operator
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./components/radix-platform/radix-operator
  prune: false
  postBuild:
    substitute:
      GIT_CLONE_TAG: "2.45.2"
      OAUTH2PROXY_TAG: "v7.15.2"
      OAUTH2REDIS_TAG: "8.6.0-alpine3.23"
      RADIX_APP_ACR_REPO_URL: radixplaygroundapp.azurecr.io
      RADIX_BUILDKIT_IMAGE_BUILDER_TAG: "1.0.0" # {"$imagepolicy": "flux-system:radix-buildkit-builder:tag"}
      RADIX_IMAGE_BUILDER_TAG: "1.0.0" # {"$imagepolicy": "flux-system:radix-image-builder:tag"}
      RADIX_OPERATOR_CHART_VERSION: 1.114.3-rc.1 # {"$imagepolicy": "flux-system:radix-operator-chart:tag"}
      RADIX_PIPELINE_GIT_CLONE_BASH_IMAGE: radixc2cache.azurecr.io/bash:5.2
      RADIX_PIPELINE_GIT_CLONE_GIT_IMAGE: radixc3cache.azurecr.io/alpine/git:2.45.2
      RADIX_PIPELINE_GIT_CLONE_NSLOOKUP_IMAGE: radixc2cache.azurecr.io/alpine:3.20
      RADIX_SECCOMP_PROFILE_INSTALLER_IMAGE: radixc2cache.azurecr.io/alpine:3.20
      SECCOMP_IMAGE_TAG: ${SECCOMP_IMAGE_TAG:=tba}
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: radix-operator
          namespace: default
        spec:
          values:
            resources:
              limits:
                cpu: "2"
                memory: 2Gi
              requests:
                cpu: 100m
                memory: 1Gi

            rbac:
              createApp:
                groups:
                  - 4b8ec60e-714c-4a9d-8e0a-3e4cfb3c3d31 # Radix Playground Users
                  - 64b28659-4fe4-4222-8497-85dd7e43e25b # Radix Platform Users
                  - 4e1761bc-0c4f-4672-a16d-7f3d8608e366 # AZAPPL Radix Platform

            radixWebhook:
              requireAdGroups: false
              requireConfigurationItem: false

      target:
        kind: HelmRelease
        name: radix-operator
        namespace: default
