apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radix-platform
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/radix-platform/radix-platform"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 2m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
    substitute:
      viewGroup: 0095272d-cb0a-4284-b1b5-86787b692627 # Entra Group "AZAPPL S941 - Contributor"
      editGroup: 47ceeaf1-4794-4291-bf1c-68f45788b66f # Entra Group "AZ PIM OMNIA RADIX Cluster Edit - dev"
      adminGroup: bed2b667-ceec-4377-83f7-46888ed23887 # Entra Group "AZ PIM OMNIA RADIX Cluster Admin - dev"
