apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radix-cost-allocation
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/radix-platform/radix-cost-allocation"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      COST_ALLOCATION_SQL_CLIENT_ID: b1a842b2-8e0e-4c2f-807e-8355eeb21f32
      COST_ALLOCATION_SQL_SERVER: sql-radix-cost-allocation-playground.database.windows.net
      RADIX_COST_ALLOCATION_CHART_VERSION: 1.4.2 # {"$imagepolicy": "flux-system:radix-cost-allocation-chart:tag"}
