apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: radix-cost-allocation
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/radix-platform/radix-cost-allocation"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      COST_ALLOCATION_SQL_CLIENT_ID: b1a842b2-8e0e-4c2f-807e-8355eeb21f32
      COST_ALLOCATION_SQL_SERVER: sql-radix-cost-allocation-playground.database.windows.net
      RADIX_COST_ALLOCATION_CHART_VERSION: 1.4.2 # {"$imagepolicy": "flux-system:radix-cost-allocation-chart:tag"}
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: radix-cost-allocation
          namespace: radix-cost-allocation
        spec:
          values:
            resources:
              limits:
                cpu: "2"
                memory: 100Mi
              requests:
                cpu: 100m
                memory: 100Mi
      target:
        kind: HelmRelease
        name: radix-cost-allocation
        namespace: radix-cost-allocation
    - patch: |- # We patch the semver.range instead of using postBuild.substitute to avoid the $quote hack when substitution variable contains YAML control characters (> and *) https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-substitution-of-numbers-and-booleans
        apiVersion: image.toolkit.fluxcd.io/v1beta2
        kind: ImagePolicy
        metadata:
          name: radix-cost-allocation-chart
          namespace: flux-system
        spec:
          policy:
            semver:
              range: '>=0.0.0-0'
      target:
        kind: ImagePolicy
        name: radix-cost-allocation-chart
        namespace: flux-system
