apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: radix-web-console-chart
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: radix-web-console-chart
  policy:
    semver:
      range: ">=0.0.0"