apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: radix-web-console-chart
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/equinor/radix/charts/radix-web-console
  ref:
    tag: ${radixWebConsoleChartVersion}