apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: clusters-${zone}
  name: ingress-nginx-ip-lb-svc
  namespace: istio-system
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  loadBalancerIP: ${ingressIP}
  ipFamilies:
    - IPv4
  ports:
  - appProtocol: tcp
    name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    gateway.networking.k8s.io/gateway-name: gateway