apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  prune: false
  postBuild:
    substitute:
      ACTIVE_CLUSTER: eu-18
      AZ_RESOURCE_DNS: radix.equinor.com
      COST_ALLOCATION_SQL_CLIENT_ID: 081fa1b1-e38b-43c0-88fe-4a4807f1798b
      COST_ALLOCATION_SQL_SERVER: sql-radix-cost-allocation-platform.database.windows.net
      FLUX_CONFIG_PATH: ./clusters/production
      RADIX_ACR_CLEANUP_CHART_VERSION: 1.4.2 # {"$imagepolicy": "flux-system:radix-acr-cleanup-chart:tag"}
      radix_acr_repo_url: radixprod.azurecr.io
      RADIX_CACHE_REGISTRY: radixplatformcache.azurecr.io
      RADIX_CICD_CANARY_CHART_VERSION: 1.5.3 # {"$imagepolicy": "flux-system:radix-cicd-canary-chart:tag"}
      RADIX_COST_ALLOCATION_CHART_VERSION: 1.4.2 # {"$imagepolicy": "flux-system:radix-cost-allocation-chart:tag"}
      RADIX_ENVIRONMENT: prod # dev | prod
      RADIX_VULNERABILITY_SCANNER_CHART_VERSION: 1.4.4 # {"$imagepolicy": "flux-system:radix-vulnerability-scanner-chart:tag"}
      RADIX_WILDCARD_CERTIFICATE_ISSUER: letsencrypt-dns01
      RADIX_ZONE_MIGRATE: platform
      RADIX_ZONE: prod # dev | playground | prod
      TEKTON_VERSION: v0.53.0
      VULNERABILITY_SCANNER_SQL_CLIENT_ID: eea03dbd-455d-4cce-895e-85d20a38ee02
      VULNERABILITY_SCANNER_SQL_SERVER: sql-radix-vulnerability-scan-platform.database.windows.net
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
