apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: lite
  targetNamespace: tekton-pipelines
  chain:
    disabled: true
  dashboard:
    options:
      disabled: true
  result:
    disabled: true
  trigger:
    disabled: false
  pruner:
    disabled: true
