apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  releaseName: istiod
  dependsOn:
  - name: istio-base
    namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: ${ISTIO_VERSION} # Set by flux patch
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    podLabels:
      grafana.radix.equinor.com/monitor-health: "true"
    
    # See https://istio.io/latest/docs/reference/commands/pilot-discovery/#envvars for options
    env:
      PILOT_ENABLE_GATEWAY_API: "true"
      PILOT_ENABLE_GATEWAY_API_STATUS: "true"
      PILOT_ENABLE_GATEWAY_API_DEPLOYMENT_CONTROLLER: "true"
      PILOT_ENABLE_ALPHA_GATEWAY_API: "true"
      PILOT_HTTP10: "true"
    
    # See https://istio.io/docs/reference/config/istio.mesh.v1alpha1/ for all available options
    meshConfig:
      accessLogFile: /dev/stdout
      accessLogEncoding: JSON
      defaultConfig:
        terminationDrainDuration: 30s # base on article https://oneuptime.com/blog/post/2026-02-24-how-to-configure-termination-drain-duration-in-istio/view
        proxyHeaders:
          envoyDebugHeaders:
            disabled: true
          server:
            disabled: true
          xForwardedPort:
            enabled: true
    global:
      logAsJson: true
      networkPolicy:
        enabled: false