apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/flux/flux-patches-base
  - flux-system
  - ./infrastructure/third-party
  - ../../components/flux/image-update-automation
  - ../../components/flux/storageclasses
  - overlay/radix-platform/radix-prometheus-proxy/patches.yaml
patches:
  - path: ./postBuild.yaml
  - path: ../../components/flux/flux-patches/helm-controller.yaml
  - path: ../../components/flux/flux-patches/image-automation-controller.yaml
  - path: ../../components/flux/flux-patches/image-reflector-controller.yaml
  - path: ../../components/flux/flux-patches/kustomize-controller.yaml
  - path: ../../components/flux/flux-patches/notification-controller.yaml
  - path: ../../components/flux/flux-patches/source-controller.yaml
