apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/flux/flux-patches-base
  - flux-system
  - ./infrastructure/third-party
  - ../../components/flux/image-update-automation
  - ../../components/flux/storageclasses
  - overlay/radix-platform/radix-prometheus-proxy/patches.yaml
patches:
  - path: ./postBuild.yaml
