apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  prune: false
  postBuild:
    substitute:
      ACTIVE_CLUSTER: weekly-24
      AZ_RESOURCE_DNS: dev.radix.equinor.com
      COST_ALLOCATION_SQL_CLIENT_ID: 89cd29bf-1e13-421c-a383-2492c1150b4c # gitleaks:allow
      COST_ALLOCATION_SQL_SERVER: sql-radix-cost-allocation-dev.database.windows.net
      FLUX_CONFIG_PATH: ./clusters/development
      RADIX_ACR_CLEANUP_CHART_VERSION: 1.4.2 # {"$imagepolicy": "flux-system:radix-acr-cleanup-chart:tag"}
      radix_acr_repo_url: radixdev.azurecr.io
      RADIX_CACHE_REGISTRY: radixdevcache.azurecr.io # use `cacheRegistry` from configmap instead
      RADIX_CICD_CANARY_CHART_VERSION: 1.5.3 # {"$imagepolicy": "flux-system:radix-cicd-canary-chart:tag"}
      RADIX_CLUSTER_CLEANUP_CHART_VERSION: 1.1.3 # {"$imagepolicy": "flux-system:radix-cluster-cleanup-chart:tag"}
      RADIX_COST_ALLOCATION_CHART_VERSION: 1.4.2 # {"$imagepolicy": "flux-system:radix-cost-allocation-chart:tag"}
      RADIX_COST_ALLOCATION_TAG: master-2f3d5136-1749723436 # {"$imagepolicy": "flux-system:radix-cost-allocation:tag"}
      RADIX_ENVIRONMENT: dev # dev | prod
      RADIX_VULNERABILITY_SCANNER_CHART_VERSION: 1.4.4 # {"$imagepolicy": "flux-system:radix-vulnerability-scanner-chart:tag"}
      RADIX_WILDCARD_CERTIFICATE_ISSUER: letsencrypt-dns01
      RADIX_ZONE_MIGRATE: dev
      RADIX_ZONE: dev # dev | playground | prod
      TEKTON_VERSION: v0.53.0
      VULNERABILITY_SCANNER_SQL_CLIENT_ID: 3eb2d577-be3f-43cf-8b12-c516d724d549 # gitleaks:allow
      VULNERABILITY_SCANNER_SQL_SERVER: sql-radix-vulnerability-scan-dev.database.windows.net
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
