apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-blackbox-exporter
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/prometheus-blackbox-exporter"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      BLACKBOX_EXPORTER_VERSION: 9.3.0 # https://artifacthub.io/packages/helm/prometheus-community/prometheus-blackbox-exporter
