apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: security-mitigation
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/security-mitigation"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system