apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - ./infrastructure/third-party
  - ./infrastructure/radix-platform
  - ../../components/flux/image-update-automation
  - ../../components/flux/namespaces
  - ../../components/flux/storageclasses
  - ./overlay/radix-platform/radix-acr-cleanup/radix-acr-cleanup.yaml
  - ./overlay/radix-platform/radix-cicd-canary/radix-cicd-canary.yaml
  - ../../components/radix-platform/radix-vulnerability-scanner
  - ../../components/radix-platform/radix-cost-allocation

patches:
  - path: ./postBuild.yaml
  - path: ./helm-controller.yaml
  - path: ./image-automation-controller.yaml
  - path: ./image-reflector-controller.yaml
  - path: ./kustomize-controller.yaml
  - path: ./notification-controller.yaml
  - path: ./source-controller.yaml
  - path: ./overlay/radix-platform/radix-vulnerability-scanner/patches.yaml
  - path: ./overlay/radix-platform/radix-cost-allocation/patches.yaml
