apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/grafana"
  dependsOn:
    - name: external-secrets-operator
    - name: kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
    substitute:
      GRAFANA_VERSION: 10.3.0 # https://artifacthub.io/packages/helm/grafana/grafana
      GRAFANA_AR_CLIENT_ID: c396d980-889d-40c9-9b52-079b325fb814 # gitleaks:allow
      GRAFANA_DB_HOST: radix-grafana-c3.mysql.database.azure.com
      GRAFANA_DB_USERNAME: radix-id-grafana-admin-c3
      GRAFANA_WI_CLIENT_ID: 3cd52da4-a716-414c-9275-96e8034ae0bd # gitleaks:allow
  wait: true
  timeout: 2m