apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-operator
  namespace: tekton-operator
spec:
  install:
    createNamespace: true
    remediation:
      retries: 3
  releaseName: tekton-operator
  chartRef:
    kind: OCIRepository
    name: tekton-operator-chart
    namespace: flux-system
  interval: 5m
