---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: monitor
spec:
  secretName: grafana-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http01-gateway
  duration: 2160h
  renewBefore: 762h
  dnsNames:
  - grafana.${clusterName}.${AZ_RESOURCE_DNS}
  - grafana.${AZ_RESOURCE_DNS}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: grafana-tls
  namespace: monitor
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: istio-system
  to:
  - group: ""
    kind: Secret
    name: grafana-tls