---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-cert
  namespace: monitor
spec:
  secretName: uptime-cert
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http01-gateway
  duration: 2160h
  renewBefore: 762h
  dnsNames:
  - uptime.${AZ_RESOURCE_DNS:=tba}
  - uptime.${clusterName:=tba}.${AZ_RESOURCE_DNS:=tba}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: uptime-cert
  namespace: monitor
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: istio-system
  to:
  - group: ""
    kind: Secret
    name: uptime-cert