apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: ${EXTERNAL_SECRET_MI_CLIENT_ID}
    azure.workload.identity/tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: flux-system
  annotations:
    azure.workload.identity/client-id: ${EXTERNAL_SECRET_MI_CLIENT_ID}
    azure.workload.identity/tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-identity-sa
  namespace: radix-cicd-canary
  annotations:
    azure.workload.identity/client-id: ${EXTERNAL_SECRET_MI_CLIENT_ID}
    azure.workload.identity/tenant-id: 3aa4a235-b6e2-48d5-9195-7fcf05b459b0

