apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: set-x-forwarded-host
  namespace: istio-system
spec:
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: envoy.filters.network.http_connection_manager
            subFilter:
              name: envoy.filters.http.router
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.lua
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua
          inlineCode: |
            function envoy_on_request(handle)
              local headers = handle:headers()
              local authority = headers:get(":authority")
              if authority == nil or authority == "" then
                authority = headers:get("host")
              end

              if authority ~= nil and authority ~= "" then
                headers:add("x-forwarded-host", authority)
              else
                headers:remove("x-forwarded-host")
              end
            end
