apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/externalsecrets-v2/stores"
  dependsOn:
    - name: external-secrets-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      EXTERNAL_SECRET_URL: https://radix-keyv-c2.vault.azure.net/
      EXTERNAL_SECRET_MI_CLIENT_ID: 88ab202e-494e-44c8-a543-a3bd0b499a87 # gitleaks:allow
  wait: true
  timeout: 2m