apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway-lb
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/gateway-lb"
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: gateway-api
  patches:
    - patch: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: istio-gateway-config
        data:
          deployment: |-
            spec:
              replicas: 5
              template:
                metadata:
                  labels:
                    grafana.radix.equinor.com/monitor-health: "true"
                spec:
                  containers:
                  - name: istio-proxy
                    resources:
                      requests:
                        cpu: 100m
                        memory: 1Gi
                      limits:
                        cpu: 2000m
                        memory: 4Gi
      target:
        kind: ConfigMap
        name: istio-gateway-config
        namespace: istio-system