apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 5m
  path: "./components/third-party/velero"
  dependsOn:
    - name: external-secrets-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
    substitute:
      VELERO_VERSION: 12.0.0 # https://artifacthub.io/packages/helm/vmware-tanzu/velero
      VELERO_PLUGIN_AZURE: v1.14.0 # https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure
      VELERO_MI_CLIENT_ID: 1275007a-e9e9-484c-af66-941d864c2a63 # gitleaks:allow
  wait: true
  timeout: 2m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: velero
      namespace: velero