# https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/

apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-gateway-config
  namespace: istio-system
data:
  service: |
    spec:
      externalTrafficPolicy: Local

  horizontalPodAutoscaler: |
    spec:
      minReplicas: 2
      maxReplicas: 5
      
      metrics:
        - resource:
            name: cpu
            target:
              averageUtilization: 80
              type: Utilization
          type: Resource
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60

  podDisruptionBudget: |
    spec:
      minAvailable: 1
