# https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/

apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-gateway-config
  namespace: istio-system
data:
  service: |
    spec:
      externalTrafficPolicy: Local

  horizontalPodAutoscaler: |
    spec:
      minReplicas: 2
      maxReplicas: 5

  podDisruptionBudget: |
    spec:
      minAvailable: 1
