apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://infra.tekton.dev/tekton-releases/operator/previous/v0.79.0/release.yaml
  - tektonconfig.yaml
patchesStrategicMerge:
  - tekton-config-defaults.yaml