apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  profile: lite
  targetNamespace: tekton-pipelines
  pruner:
    disabled: true
    # resources:
    # - pipelinerun
    # - taskrun
    # keep: 100
    # schedule: "0 8 * * *"