apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  prune: false
  postBuild:
    substitute:
      AZ_RESOURCE_DNS: playground.radix.equinor.com
      FLUX_CONFIG_PATH: ./clusters/playground
      radix_acr_repo_url: radixplayground.azurecr.io
      RADIX_CACHE_REGISTRY: radixplaygroundcache.azurecr.io
      RADIX_ENVIRONMENT: dev # dev | prod
      RADIX_WILDCARD_CERTIFICATE_ISSUER: letsencrypt-dns01
      RADIX_ZONE_MIGRATE: playground
      RADIX_ZONE: playground # dev | playground | prod
      TEKTON_VERSION: v0.53.0
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
