apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: radix-operator-chart
  namespace: flux-system
spec:
  interval: 1m
  url: oci://ghcr.io/richard87/radix-charts/radix-operator # oci://ghcr.io/equinor/radix/charts/radix-operator
  ref:
    tag: 1.114.2-test4 # ${RADIX_OPERATOR_CHART_VERSION} # Set in cluster postBuild.yaml
