apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: grafana-chart
  namespace: flux-system
spec:
  image: ghcr.io/grafana-community/helm-charts/grafana
  interval: 1m0s
