apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: grafana-chart
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: grafana-chart
  policy:
    semver:
      range: "<=12.10.3 >=1.0.0"
