apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  prune: false
  postBuild:
    substitute:
      ACTIVE_CLUSTER: c2-11
      AZ_RESOURCE_DNS: c2.radix.equinor.com
      CERT_MANAGER_CLUSTER_ISSUER_DNZ_ZONE_MI: abdbd354-57e3-4bac-9fc6-b99ef03c0905 # MI radix-id-certmanager-c2
      CERT_MANAGER_DNZ_ZONE_RESOURCE_GROUP: common-c2
      CERT_MANAGER_VERSION: 1.19.2 # https://artifacthub.io/packages/helm/cert-manager/cert-manager
      COST_ALLOCATION_SQL_CLIENT_ID: e48dda41-942a-4b25-94a6-c017014abaa9
      COST_ALLOCATION_SQL_SERVER: sql-radix-cost-allocation-c2.database.windows.net
      EXTMON_CLUSTER_ISSUER: "https://northeurope.oic.prod-aks.azure.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/a2d93ba1-cbde-4408-8979-c100cce7b448/"
      FLUX_CONFIG_PATH: ./clusters/c2-production
      KEDA_VERSION: 2.18.3 # https://artifacthub.io/packages/helm/kedacore/keda
      KUBE_PROMETHEUS_STACK: 81.3.2 # https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
      NGINX_VERSION: 4.14.1 # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
      OAUTH2PROXY_TAG: "v7.15.2"
      OAUTH2REDIS_TAG: "8.6.0-alpine3.23" # gitleaks:allow
      RADIX_ACR_CLEANUP_CHART_VERSION: 1.4.2 # {"$imagepolicy": "flux-system:radix-acr-cleanup-chart:tag"}
      radix_acr_repo_url: radixc2prod.azurecr.io
      RADIX_CACHE_REGISTRY: radixc2cache.azurecr.io
      RADIX_CICD_CANARY_CHART_VERSION: 1.5.3 # {"$imagepolicy": "flux-system:radix-cicd-canary-chart:tag"}
      RADIX_COST_ALLOCATION_CHART_VERSION: 1.4.2 # {"$imagepolicy": "flux-system:radix-cost-allocation-chart:tag"}
      RADIX_ENVIRONMENT: prod # dev | prod
      RADIX_OAUTH_GUARD_CHART_VERSION: 1.1.2 # {"$imagepolicy": "flux-system:radix-oauth-guard-chart:tag"}
      RADIX_VULNERABILITY_SCANNER_CHART_VERSION: 1.4.4 # {"$imagepolicy": "flux-system:radix-vulnerability-scanner-chart:tag"}
      RADIX_WILDCARD_CERTIFICATE_ISSUER: letsencrypt-dns01
      RADIX_ZONE_MIGRATE: c2
      RADIX_ZONE: c2 # dev | playground | prod
      TEKTON_VERSION: v0.53.0
      VULNERABILITY_SCANNER_SQL_CLIENT_ID: 7264db03-2c4a-47b7-87d2-1bdfcc188131
      VULNERABILITY_SCANNER_SQL_SERVER: sql-radix-vulnerability-scan-c2.database.windows.net
    substituteFrom:
      - kind: ConfigMap
        name: radix-flux-config
