name: Check for new versions
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      zone:
        description: 'Zone to check'
        required: false
        type: choice
        options:
          - 'all'
          - 'c2'
          - 'c3'
          - 'dev'
          - 'monitor'
          - 'playground'
          - 'platform'

permissions: {}
jobs:
  check-version:
    name: Check for new versions (${{ matrix.zone }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        zone:
          - c2
          - c3
          - dev
          - monitor
          - playground
          - platform
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: checkout
        if: github.event_name != 'workflow_dispatch' || inputs.zone == 'all' || inputs.zone == matrix.zone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set environments
        if: github.event_name != 'workflow_dispatch' || inputs.zone == 'all' || inputs.zone == matrix.zone
        run: |
          DATE_STAMP="$(date +%Y-%m-%d)"
          ZONE="${{ matrix.zone }}"
          PR_BRANCH_TEMP="automatic-version-update"
          PR_NAME_TEMP="Automatic Pull Request"

          echo "ZONE=${ZONE}" >> $GITHUB_ENV
          echo "PR_BRANCH=${PR_BRANCH_TEMP}-${ZONE}" >> $GITHUB_ENV
          echo "PR_NAME=${PR_NAME_TEMP} - ${ZONE} - ${DATE_STAMP}" >> $GITHUB_ENV

      - name: Check version
        if: github.event_name != 'workflow_dispatch' || inputs.zone == 'all' || inputs.zone == matrix.zone
        id: checkversion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZONE: ${{ env.ZONE }}
        run: .github/workflows/scripts/update_components.sh

      - name: Create PR
        if: (github.event_name != 'workflow_dispatch' || inputs.zone == 'all' || inputs.zone == matrix.zone) && steps.checkversion.outputs.numberOfChanges > 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          PR_BRANCH: ${{ env.PR_BRANCH }}
          PR_NAME: ${{ env.PR_NAME }}
        run: .github/workflows/scripts/create_pr.sh
